### ISSUE TITLE
Some Bones dialog in Fort Fatras is messed up.

### ISSUE THREAD

**Issue by TheShadowRunner** [Krokodyl/treasure-conflix#2]
Playing on SD2SNES, i just got this overlapping text issue, please check image.
![DSC_0149](https://user-images.githubusercontent.com/1895340/207979553-6b7ff80b-2336-4d27-8f62-58c245bafc35.JPG)

**Comment by Krokodyl** [comment]
Noted.

**Comment by Krokodyl** [comment]
![BS Treasure Conflix (English) - SNES - extended000](https://user-images.githubusercontent.com/3762526/208486864-407826a1-6be5-4cc8-b8e6-836c48fe807b.png)
![BS Treasure Conflix (English) - SNES - extended001](https://user-images.githubusercontent.com/3762526/208486867-f42ca74c-c660-43d2-8b97-f304bf86404f.png)

Just adding two screenshots for future references.
